name: video_viewer
description: Multiplatform minimalist video viewer with spectacular user experience.
homepage: https://github.com/seel-channel/video_viewer
version: 1.2.7

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  http: ^1.5.0
  path_provider: ^2.1.3
  video_player: ^2.10.0
  video_player_web_hls: ^1.3.0
  wakelock_plus: ^1.4.0
  volume_watcher: ^2.0.1
  gesture_x_detector: ^1.1.1
  helpers: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
